# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: au.csiro.fhir.au-item-715
canonical: https://aehrc.com/fhir/item715
name: item-715-data
title: Aboriginal and Torres Strait Islander health check
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: CSIRO
  url: https://github.com/aehrc
  email: Michael.Lawley@csiro.au 
dependencies:
  hl7.fhir.au.base: current
  au.csiro.fhir.au-primarycare: current
  hl7.fhir.uv.sdc: current

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Capability: CapabilityStatement-AUItem715SearchRequirementDescription.html
  MBS 715 Form: Questionnaire-mbs715.html

